name: Debug

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build APK (NormalDebug)
        run: ./gradlew assembleNormalDebug

      - name: Delete Old Artifacts
        uses: actions/github-script@v6
        id: artifact
        with:
          script: |
            const res = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          
            for (const artifact of res.data.artifacts) {
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                })
            }

      - name: Upload Artifact (Backup)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.run_number }}
          path: app/build/outputs/apk/normal/debug/*.apk

      - name: Create & Upload Debug Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: debug-v${{ github.run_number }}
          name: Debug Build v${{ github.run_number }}
          body: |
            Debug build for testing.
            Build Number: ${{ github.run_number }}
          draft: false
          prerelease: true
          files: app/build/outputs/apk/normal/debug/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
